# Generated by Django 4.0.2 on 2022-02-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevhunterapp', '0002_remove_technologie_developers_developer_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
    ]
