# Generated by Django 4.0.2 on 2022-02-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevhunterapp', '0003_developer_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.CharField(default='https://rouelibrenmaine.fr/wp-content/uploads/2018/10/empty-avatar.png', max_length=500),
        ),
    ]
