# Generated by Django 4.0.2 on 2022-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevhunterapp', '0005_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(default='https://www.projz.com/static/media/screenshot1.d9c4e990.png', max_length=500),
        ),
    ]
