# Generated by Django 4.0.2 on 2022-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevhunterapp', '0006_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='https://github.com', max_length=500),
        ),
    ]
