# Generated by Django 4.0.2 on 2022-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevhunterapp', '0007_project_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
